### ISSUE TITLE
Add it on F-Droid

### ISSUE THREAD

**Issue by ghost** [streblow/PaperRacing#1]
Cast @IzzySoft

**Comment by streblow** [comment]
Sorry, publishing on F-Droid seems to be a challenge I am not willing to accept!
This project is still under construction and so not really ready for publishing just for testing.

**Comment by IzzySoft** [comment]
@streblow not going to publish any APK at all – or just not as public as the official F-Droid repo? How shall your testers test? :wink: Maybe you'd consider publishing the APK here at Github, see [Creating Releases (GitHub Help)](https://help.github.com/articles/creating-releases/)?

@Symbian9 please do not just "cast" me without giving context. You're always welcome asking me for help, but then details are needed – not just mentioning my nick. Thanks!

**Comment by streblow** [comment]
Just added a release, though it isn't a really release - just a functional beta. Now all guys should find an easy link to the APK for this android app.

**Comment by IzzySoft** [comment]
Thanks a lot, @streblow! Taking a look inside, v0.9 identifies itself as

    package: name='de.streblow.paperracing' versionCode='1' versionName='1.0' platformBuildVersionName=''

Not sure if that's intended, but shouldn't `versionName` be "0.9" and `versionCode` something bigger than 1 (as it must be increased with every new version, because that's what Android looks at when telling whether it's an update)?

**Comment by streblow** [comment]
The release area now contains a APK with consistent version information. I will release new version when I've added new features (like championship mode)
